server:
  port: 80
  servlet:
    context-path: /wechat

spring:
  application:
    name: platform-wechat

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: "jdbc:mysql://47.92.64.11:3306/foolday_platform?
      useUnicode=true&characterEncoding=UTF-8&useSSL=false&
      serverTimezone=Asia/Shanghai&autoReconnect=true&failOverReadOnly=false"
    username: foolday_platform
    password: dc@tiny401
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 10
        prepStmtCacheSqlLimit: 16
        useServerPrepStmts: true
        maximumPoolSize: 4

    tomcat:
      max-wait: 10000
      max-active: 50
      test-on-borrow: true
  servlet:
    multipart.max-file-size: 10Mb
    multipart:
      max-request-size: 100Mb
  redis:
    database: 0
    host: 47.92.64.11
    password:
    port: 6379

mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:/com/foolday/dao/*/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔 com.yourpackage.*.entity
  typeAliasesPackage: com.foolday.dao.*
  # 支持统配符 * 或者 ; 分割
  typeEnumsPackage: com.foolday.common.enums
  # 自动配置中已Map来存储
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 3
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #mp2.3+ 全局表前缀 mp_
    #table-prefix: mp_
    #刷新mapper 调试神器
    #refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    # Sequence序列接口实现类配置
    key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 1
    logic-not-delete-value: 0
  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    cache-enabled: false
    #配置JdbcTypeForNull, oracle数据库必须配置
    jdbc-type-for-null: 'null'

logging:
  level:
    ROOT: INFO
    com.foolday: DEBUG


# 平台配置
platform:
  web:
    session:
      openTestSession: false
      testOpenId: oTeUN5Mz09IIvYtMAREUUm1fsGnA
  # 图片定制
  image:
    # 支持的文件类型
    enable-content-type:
      - png
        jpeg
        jpg
        gif
    # 存储在磁盘目录
    store-path: /home/image

# 下面是微信相关的配置
wechat:
  myOpenId: oxFFT0XhOLz-MeFpTMZ35kWFOaoM # 模拟客户身份1
  toOpenId: oxFFT0Zfl2w5SWyYTH8bT91FHiYE # 模拟客户身份2
  #  mpAppId: wxdcf91e9f784bfad0
  #  mpAppSecret: c467c06d98a2447f5ddef6ca8f47f268 #测试号appId,appSecret
  mpappId: wxe8650214ca46a5c9
  mpAppSecret: 4a027a82f8fa2ee453a679d7b4a4ac01 #借用号appId,appSecret
  openAppId: wxef923e99135107cb
  openAppSecret: 0b70ab77cd3432365b9bbe20448083d0 #开放平台测试号appId,appSecret
  mchId: 1483469312
  mchKey: C5245D70627C1F8E9964D494B0735025
  keyPath: ./pay_key/apiclient_cert.p12
  notifyUrl: http://j58v2f.natappfree.cc/wechat/auth
  templateId:
    orderStatus: GoCullfix05R-rCibvoyI87ZUg50cyieKA5AyX7pPzo

# 基于weixin-sdk的配置
wx:
  miniapp:
    configs:
      - appId: wxe8650214ca46a5c9 #微信小程序的appid 小程序的appid,前端需要提供来确保对应的配置信息
        secret: 4a027a82f8fa2ee453a679d7b4a4ac01 #微信小程序的Secret
        token: my2019token #微信小程序消息服务器配置的token
        aesKey: wW7fORMF45k7JRrGpGACzPz5bOlCxNyhWOOhZowoGHA #微信小程序消息服务器配置的EncodingAESKey
  pay:
    appId: wxe8650214ca46a5c9 #微信公众号或者小程序等的appid
    mchId: 1543442491 #微信支付商户号
    mchKey: trXdYY9InKllVfQWjRKAHx10saKHm0Np #微信支付商户密钥
    subAppId: #服务商模式下的子商户公众账号ID
    subMchId: #服务商模式下的子商户号
    keyPath: classpath:pay_key/apiclient_cert.p12 # p12证书的位置，可以指定绝对路径，也可以指定类路径（以classpath:开头）
  mp:
    configs:
      - appId: wxe8650214ca46a5c9 #（一个公众号的appid）
        secret: 4a027a82f8fa2ee453a679d7b4a4ac01 #（公众号的appsecret）
        token: my2019token #（接口配置里的Token值）
        aesKey: wW7fORMF45k7JRrGpGACzPz5bOlCxNyhWOOhZowoGHA #（接口配置里的EncodingAESKey值）
        contactPhone: 1881312121 # 开发票中需要联系电话号码