server:
  port: 8080

spring:
  application:
    name: platform

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/foolday_platform?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 10
        prepStmtCacheSqlLimit: 16
        useServerPrepStmts: true
        maximumPoolSize: 5

    tomcat:
      max-wait: 10000
      max-active: 50
      test-on-borrow: true
  servlet:
    multipart.max-file-size: 10Mb
    multipart:
      max-request-size: 100Mb
  redis:
    database: 1 
    host: localhost
    password:
    port: 6379

# pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check

logging:
  level:
    ROOT: INFO
    cn.fooltech: DEBUG

mybatis:
  type-aliases-package: cn.fooltech
  # classpath* 用于加载类路径（包括jar包）中的所有匹配的资源,扫描项目包下所有xml, 而非resource下
  mapper-locations: classpath*:cn/**/mapper/*.xml
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 3
  configuration:
    map-underscore-to-camel-case: true