spring:
  profiles:
    active:
    - prod
  auto:
    openUrl: false
  web:
    loginUrl: http://localhost:port/context/swagger-ui.html
    blowserExecute: C://Program Files (x86)//Google//Chrome//Application//chrome.exe