spring:
  profiles:
    active:
    - prod
  auto:
    openUrl: false
  web:
    loginUrl: http://localhost:port/context/swagger-ui.html
    blowserExecute: C://Program Files (x86)//Google//Chrome//Application//chrome.exe
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 20MB
  thymeleaf:
    cache: false
    prefix: classpath:/static/
    redis:
      host: 47.92.64.11
      port: 6379
      password:
      jedis:
        pool:
          max-idle: 8 # 连接池最大连接数（使用负值表示没有限制）
          max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
          max-wait: -1s # 连接池最大阻塞等待时间（使用负值表示没有限制）
          min-idle: 0 # 连接池中的最小空闲连接
      timeout: 3s # 连接超时时间（秒）
  datasource:
    url: jdbc:mysql://47.92.64.11:3306/hotel?userSSL=true&useUnicode=true&characterEncoding=UTF8&serverTimezone=Asia/Shanghai
    username: hotel
    password: hotel@123
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: select 1
    jpa:
      database: MYSQL
      show-sql: true
      hibernate:
        ddl-auto: update
        naming: #命名策略
          implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
wx:
  appId: wx9ee98bd4f8d11ff0
  secret: sectet
  wxLoginUrl: wxLoginUrl
  mchId: 1519432861
  key: QJuulKkgDeV6ubAYFX9WaZcS1ucj1oSU
  certPath: apiclient_cert.p12
  notify_url: /api/wxPay/notify           #支付成功回调地址
  refund_url: /api/wxPay/refund           #退款成功回调地址
my:
  project:
    upload-path: static  #上传下载路径
    default-photo: /uploadFile/2019/7/0/(1561183246487)timg.png            #默认头像
system:
  sysAdmin:
    name: 系统管理员Admin
    phone: 18319254427
    password: 111
  userLevel:
    name: 青铜
    required-points: 0